###############################################
#######        O U T P U T         ############
###############################################

#/gate/output/ascii/enable
##/gate/output/ascii/setFileName ../../../../home/hsihao/DHAPET
#/gate/output/ascii/setFileName 	COINCIDENCES
#/gate/output/ascii/setOutFileHitsFlag 0
#/gate/output/ascii/setOutFileSinglesFlag 0
#/gate/output/ascii/setOutFileCoincidencesFlag 1
#/gate/output/ascii/setCoincidenceMask 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0
##/gate/output/ascii/setCoincidenceMask 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
##/gate/output/ascii/setOutFiledelayFlag 0
#/gate/output/ascii/setOutFileSizeLimit 4000000000
##/gate/output/BasicROOT/setFileName  test.root
#
/gate/output/root/enable
/gate/output/root/setFileName out/DETECTOR_DATA_100MeV_2mins_230309_4.0MeVsig
/gate/output/root/setRootNtupleFlag 0
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setSaveRndmFlag 1














